package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.GoodsInfo;
import xyz.foolcat.model.GoodsInfoExample;

public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    long countByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int deleteByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    @Insert({
        "insert into foolcat_goods_info (shop_id, goods_name, ",
        "goods_description, goods_type, ",
        "goods_url, price, ",
        "click_count, sale_volume, ",
        "stock_count, create_time, ",
        "update_time)",
        "values (#{shopId,jdbcType=VARCHAR}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{goodsDescription,jdbcType=VARCHAR}, #{goodsType,jdbcType=INTEGER}, ",
        "#{goodsUrl,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=xyz.foolcat.handler.MoneyTypeHandler}, ",
        "#{clickCount,jdbcType=BIGINT}, #{saleVolume,jdbcType=BIGINT}, ",
        "#{stockCount,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    List<GoodsInfo> selectByExampleWithRowbounds(GoodsInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    List<GoodsInfo> selectByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int updateByExample(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);
}