package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.GoodsInfo;
import xyz.foolcat.model.GoodsInfoExample;

public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    long countByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int deleteByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Delete({
        "delete from foolcat_goods_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Insert({
        "insert into foolcat_goods_info (id, shop_id, goods_name, ",
        "goods_description, goods_type, ",
        "goods_url, price, ",
        "click_count, sale_volume, ",
        "stock_count, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{shopId,jdbcType=VARCHAR}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{goodsDescription,jdbcType=VARCHAR}, #{goodsType,jdbcType=INTEGER}, ",
        "#{goodsUrl,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=xyz.foolcat.handler.MoneyTypeHandler}, ",
        "#{clickCount,jdbcType=BIGINT}, #{saleVolume,jdbcType=BIGINT}, ",
        "#{stockCount,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT REPLACE(UUID(),'-','') FROM DUAL", keyProperty="id", before=true, resultType=String.class)
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<GoodsInfo> selectByExampleWithRowbounds(GoodsInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<GoodsInfo> selectByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Select({
        "select",
        "id, shop_id, goods_name, goods_description, goods_type, goods_url, price, click_count, ",
        "sale_volume, stock_count, create_time, update_time",
        "from foolcat_goods_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.GoodsInfoMapper.BaseResultMap")
    GoodsInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExample(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_goods_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Update({
        "update foolcat_goods_info",
        "set shop_id = #{shopId,jdbcType=VARCHAR},",
          "goods_name = #{goodsName,jdbcType=VARCHAR},",
          "goods_description = #{goodsDescription,jdbcType=VARCHAR},",
          "goods_type = #{goodsType,jdbcType=INTEGER},",
          "goods_url = #{goodsUrl,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=BIGINT,typeHandler=xyz.foolcat.handler.MoneyTypeHandler},",
          "click_count = #{clickCount,jdbcType=BIGINT},",
          "sale_volume = #{saleVolume,jdbcType=BIGINT},",
          "stock_count = #{stockCount,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsInfo record);
}