package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.ShopInfo;
import xyz.foolcat.model.ShopInfoExample;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    long countByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int deleteByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Delete({
        "delete from foolcat_shop_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Insert({
        "insert into foolcat_shop_info (id, user_id, shop_name, ",
        "shop_background_image_url, shop_portrait_url, ",
        "state, shop_description, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, #{shopName,jdbcType=VARCHAR}, ",
        "#{shopBackgroundImageUrl,jdbcType=VARCHAR}, #{shopPortraitUrl,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=INTEGER}, #{shopDescription,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT REPLACE(UUID(),'-','') FROM DUAL", keyProperty="id", before=true, resultType=String.class)
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<ShopInfo> selectByExampleWithRowbounds(ShopInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<ShopInfo> selectByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Select({
        "select",
        "id, user_id, shop_name, shop_background_image_url, shop_portrait_url, state, ",
        "shop_description, create_time, update_time",
        "from foolcat_shop_info",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.ShopInfoMapper.BaseResultMap")
    ShopInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByPrimaryKeySelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Update({
        "update foolcat_shop_info",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "shop_name = #{shopName,jdbcType=VARCHAR},",
          "shop_background_image_url = #{shopBackgroundImageUrl,jdbcType=VARCHAR},",
          "shop_portrait_url = #{shopPortraitUrl,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "shop_description = #{shopDescription,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ShopInfo record);
}