package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.ShopInfo;
import xyz.foolcat.model.ShopInfoExample;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    long countByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    int deleteByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    @Insert({
        "insert into foolcat_shop_info (user_id, shop_name, ",
        "shop_background_image_url, shop_portrait_url, ",
        "state, shop_description, ",
        "create_time, update_time)",
        "values (#{userId,jdbcType=VARCHAR}, #{shopName,jdbcType=VARCHAR}, ",
        "#{shopBackgroundImageUrl,jdbcType=VARCHAR}, #{shopPortraitUrl,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=INTEGER}, #{shopDescription,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    List<ShopInfo> selectByExampleWithRowbounds(ShopInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    List<ShopInfo> selectByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_shop_info
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);
}