package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.Swiper;
import xyz.foolcat.model.SwiperExample;

public interface SwiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    long countByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int deleteByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Delete({
        "delete from foolcat_swiper",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Insert({
        "insert into foolcat_swiper (id, shop_id, swiper_image_url, ",
        "title, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{shopId,jdbcType=VARCHAR}, #{swiperImageUrl,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT REPLACE(UUID(),'-','') FROM DUAL", keyProperty="id", before=true, resultType=String.class)
    int insert(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int insertSelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<Swiper> selectByExampleWithRowbounds(SwiperExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<Swiper> selectByExample(SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Select({
        "select",
        "id, shop_id, swiper_image_url, title, create_time, update_time",
        "from foolcat_swiper",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.SwiperMapper.BaseResultMap")
    Swiper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Swiper record, @Param("example") SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExample(@Param("record") Swiper record, @Param("example") SwiperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByPrimaryKeySelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Update({
        "update foolcat_swiper",
        "set shop_id = #{shopId,jdbcType=VARCHAR},",
          "swiper_image_url = #{swiperImageUrl,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Swiper record);
}