package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.Theme;
import xyz.foolcat.model.ThemeExample;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    long countByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int deleteByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Delete({
        "delete from foolcat_theme",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Insert({
        "insert into foolcat_theme (id, theme_name, theme_image_url, ",
        "state, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=VARCHAR}, #{themeName,jdbcType=VARCHAR}, #{themeImageUrl,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT REPLACE(UUID(),'-','') FROM DUAL", keyProperty="id", before=true, resultType=String.class)
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<Theme> selectByExampleWithRowbounds(ThemeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<Theme> selectByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Select({
        "select",
        "id, theme_name, theme_image_url, state, create_time, update_time",
        "from foolcat_theme",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.ThemeMapper.BaseResultMap")
    Theme selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExample(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByPrimaryKeySelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Update({
        "update foolcat_theme",
        "set theme_name = #{themeName,jdbcType=VARCHAR},",
          "theme_image_url = #{themeImageUrl,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Theme record);
}