package xyz.foolcat.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.Theme;
import xyz.foolcat.model.ThemeExample;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    long countByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int deleteByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    @Insert({
        "insert into foolcat_theme (theme_name, theme_image_url, ",
        "state, create_time, ",
        "update_time)",
        "values (#{themeName,jdbcType=VARCHAR}, #{themeImageUrl,jdbcType=VARCHAR}, ",
        "#{state,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    List<Theme> selectByExampleWithRowbounds(ThemeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    List<Theme> selectByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_theme
     *
     * @mbg.generated Sun Jul 14 21:54:20 CST 2019
     */
    int updateByExample(@Param("record") Theme record, @Param("example") ThemeExample example);
}