package xyz.foolcat.mapper;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import xyz.foolcat.model.UserInfo;
import xyz.foolcat.model.UserInfoExample;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Delete({
            "delete from foolcat_sys_user_info",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Insert({
            "insert into foolcat_sys_user_info (id, union_id, nick_name, ",
            "portrait_url, user_identity, ",
            "phone, sex, create_time, ",
            "update_time)",
            "values (#{id,jdbcType=VARCHAR}, #{unionId,jdbcType=VARCHAR}, #{nickName,jdbcType=VARCHAR}, ",
            "#{portraitUrl,jdbcType=VARCHAR}, #{userIdentity,jdbcType=INTEGER}, ",
            "#{phone,jdbcType=VARCHAR}, #{sex,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement = "SELECT REPLACE(UUID(),'-','') FROM DUAL", keyProperty = "id", before = true, resultType = String.class)
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<UserInfo> selectByExampleWithRowbounds(UserInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Select({
            "select",
            "id, union_id, nick_name, portrait_url, user_identity, phone, sex, create_time, ",
            "update_time",
            "from foolcat_sys_user_info",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.UserInfoMapper.BaseResultMap")
    UserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_sys_user_info
     *
     * @mbg.generated Tue Aug 13 14:52:18 CST 2019
     */
    @Update({
            "update foolcat_sys_user_info",
            "set union_id = #{unionId,jdbcType=VARCHAR},",
            "nick_name = #{nickName,jdbcType=VARCHAR},",
            "portrait_url = #{portraitUrl,jdbcType=VARCHAR},",
            "user_identity = #{userIdentity,jdbcType=INTEGER},",
            "phone = #{phone,jdbcType=VARCHAR},",
            "sex = #{sex,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserInfo record);

    /**
     * 通过unionId 查找用户信息
     *
     * @param unionId
     * @return UserInfo 对象 或 NULL
     */
    @Select({
            "select",
            "id, union_id, nick_name, portrait_url, user_identity, phone, sex, create_time, ",
            "update_time",
            "from foolcat_sys_user_info",
            "where union_id = #{unionId,jdbcType=VARCHAR}"
    })
    @ResultMap("xyz.foolcat.mapper.UserInfoMapper.BaseResultMap")
    UserInfo selectByUnionId(String unionId);
}