server:
  port: 8090
logging:
  level:
    root: debug
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foolcat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 5
      filters: config,stat,slf4j
      stat-view-servlet:
        enabled: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
  redis:
    host: localhost
    jedis:
      pool:
        max-active: 8
        max-wait: 300ms
        max-idle: 4
        min-idle: 2
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: xyz.foolcat.model
  type-handlers-package: xyz.foolcat.handler
  configuration:
    map-underscore-to-camel-case: true
wechat:
  app-id: wx5e6c79f09b43dee8
  app-secret: 408aa9493e2bcf7105668c30ed8993ec
  api-url: https://api.weixin.qq.com
