spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foolcat
    username: foolcat
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 5
      filters: config,stat,slf4j
      stat-view-servlet:
        enabled: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: xyz.foolcat.model
  type-handlers-package: xyz.foolcat.handler
  configuration:
    map-underscore-to-camel-case: true
wechat:
  app-id:
  app-secret: