spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foolcat
    username: foolcat
    password: M3efb4/rrwBvHdAcHj2m4ZesL5z1pCV4KI58xBpJtONTsIE8FSFFDqW8CFfXyvZ1wWBlwxHk9ECx8HWztJg0TQ==
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 5
      filters: config,stat,slf4j
      stat-view-servlet:
        enabled: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIe39Fnk+94kl0yR1TYhnu7s5L9tM+7S0tJTzhMnKnw99BvR2lkKCUw6cmFPY59T/PqJ6aftbNQ34vnKhiLDPs8CAwEAAQ==
  redis:
    host: 127.0.0.1
    password: foolcat.123
    jedis:
      pool:
        max-active: 8
        max-wait: 3000ms
        max-idle: 4
        min-idle: 2
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: xyz.foolcat.model
  type-handlers-package: xyz.foolcat.handler
  configuration:
    map-underscore-to-camel-case: true
wechat:
  app-id: wx5e6c79f09b43dee8
  app-secret: 408aa9493e2bcf7105668c30ed8993ec
  api-url: https://api.weixin.qq.com