package xyz.foolcat.model;

import java.io.Serializable;
import java.util.Date;

public class Swiper implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.shop_id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.swiper_image_url
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private String swiperImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.title
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.create_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foolcat_swiper.update_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.id
     *
     * @return the value of foolcat_swiper.id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.id
     *
     * @param id the value for foolcat_swiper.id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.shop_id
     *
     * @return the value of foolcat_swiper.shop_id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withShopId(String shopId) {
        this.setShopId(shopId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.shop_id
     *
     * @param shopId the value for foolcat_swiper.shop_id
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.swiper_image_url
     *
     * @return the value of foolcat_swiper.swiper_image_url
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public String getSwiperImageUrl() {
        return swiperImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withSwiperImageUrl(String swiperImageUrl) {
        this.setSwiperImageUrl(swiperImageUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.swiper_image_url
     *
     * @param swiperImageUrl the value for foolcat_swiper.swiper_image_url
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setSwiperImageUrl(String swiperImageUrl) {
        this.swiperImageUrl = swiperImageUrl == null ? null : swiperImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.title
     *
     * @return the value of foolcat_swiper.title
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.title
     *
     * @param title the value for foolcat_swiper.title
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.create_time
     *
     * @return the value of foolcat_swiper.create_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.create_time
     *
     * @param createTime the value for foolcat_swiper.create_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foolcat_swiper.update_time
     *
     * @return the value of foolcat_swiper.update_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public Swiper withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foolcat_swiper.update_time
     *
     * @param updateTime the value for foolcat_swiper.update_time
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foolcat_swiper
     *
     * @mbg.generated Tue Jul 30 23:49:45 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shopId=").append(shopId);
        sb.append(", swiperImageUrl=").append(swiperImageUrl);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}